version: '2'
services:
    # client:
    #     container_name: client
    #     build: ./client
    #     volumes:
    #         - "./client:/app_src"
    #     command: npm start
    #     environment:
    #         REACT_APP_GRAPHQL_URI: http://192.168.99.100:4000/graphql
    #     ports:
    #         - "3000:3000"
    server:
        container_name: server
        build: ./server
        volumes:
            - "./server:/app_src"
        command: npm start
        ports:
            - "4000:4000"
